<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApplicationForm extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $query="INSERT INTO `application_forms` (`id`, `position_applied`, `attached_doc`, `passport_brp_others`, `min_letter_proof_other`, `profile_image`, `name`, `surname`, `forename`, `surname_of_birth`, `date_of_birth`, `current_address`, `post_code`, `from`, `to`, `previous_address`, `post_code_prev`, `from_prev`, `to_prev`, `from_last`, `to_last`, `email`, `mobile`, `telephone`, `nationality`, `date_and_place_enter_in_uk`, `visa_type`, `national_insurance_no`, `passport_number`, `sia_license_sect`, `sia_license_no`, `sia_license_expiry`, `type_driving_license`, `own_passport`, `driving_license_no`, `dvla_license_check_code`, `disquilifed`, `motoring_`, `offence`, `equal_opportunities`, `purpose_job_accept`, `application_name`, `ni_number`, `applicant_signature`, `appli_date`, `employee_name`, `job_title`, `employee_id`, `photogrphs`, `i_name`, `employee_signature`, `employee_date`, `agreement_company`, `agreement_employee`, `staff_name`, `staff_sign`, `staff_date`, `company_represent_name`, `company_represent_sign`, `stacompany_represent_date`, `ethnic`, `created_at`, `updated_at`) VALUES
(1, 'Deserunt delectus q', 'application_form/documents/1754428003_document (4).pdf', 'Dignissimos quisquam', 'Expedita culpa cupi', 'application_form/profile/1754428003_team-image1.jpg', 'Yuli Hoffman', 'Morales', 'Randall Galloway', 'Glenn', '12-Aug-2000', 'Porro exercitation n', 'Id velit autem fugit', 'Eaque sed ipsum rep', 'Quam ut in voluptas', 'In et rerum dolores', 'Amet quam nihil dol', 'Perferendis alias a', 'Alias voluptate est', 'Eos placeat occaec', 'Pariatur Itaque rec', 'wurovibyvo@mailinator.com', 'Tempore non aut rem', '+1 (675) 866-5879', 'Omnis non ut reprehe', '23-Feb-1992', 'Sed aliqua Tempore', 'Cupidatat lorem aper', '828', 'Consequat Totam in', 'Autem in aperiam ess', 'Eaque sint at verit', 'Consequuntur harum e', 'Laboris saepe volupt', 'Qui commodi labore b', 'Doloremque possimus', 'Dicta non a occaecat', 'Sit laboriosam dolo', 'Et error libero sunt', 'Other', 'on', 'Burke Stone', '150', 'Officia fugiat odio', '2007-05-23', 'Sebastian Ramirez', 'Adipisicing aliquid', 'Eligendi blanditiis', NULL, 'Lane Richard', 'Pariatur Voluptatib', '15-Oct-1982', 'Wolf Mckay Trading', 'Amet quidem laborum', 'Rigel Turner', 'Ut consequatur facil', '03-Nov-2003', 'Delgado Joseph Co', 'Larson Hobbs Associates', 'Cox Keith Plc', 'Voluptatem Architec', '2025-08-05 16:06:43', '2025-08-05 16:06:43'),
(2, 'Placeat distinctio', 'application_form/documents/1755252128_image-Picsart-AiImageEnhancer.png', 'Quidem temporibus al', 'Sit labore voluptat', 'application_form/profile/1755252128_video.jpg', 'Zachary Hurst', 'Brewer', 'Shaeleigh Matthews', 'Middleton', '23-Feb-1998', 'Possimus ullam volu', 'Eiusmod suscipit in', 'Vero consequatur Do', 'Ut in aliquam in ips', 'Dolore totam qui odi', 'Dolor repudiandae cu', 'Consequatur fugiat', 'Id impedit sit magn', 'Eius iste officia es', 'Quo commodo ipsam qu', 'jexewesu@mailinator.com', 'Inventore sed volupt', '+1 (577) 863-5412', 'Nulla nemo provident', '12-Dec-1988', 'Vitae magni exercita', 'Dignissimos cillum i', '797', 'Sed commodo repellen', 'Est nobis eveniet', 'Architecto ad dolore', 'Veniam fuga Velit', 'Officiis ut optio i', 'Vel nostrud quis eli', 'Ut in sit quasi cons', 'Nulla quibusdam susc', 'Consequatur et et si', 'Est similique omnis', 'Other', 'on', 'Jade Meadows', '274', 'Aut dolores pariatur', '1998-04-16', 'Yoko Bruce', 'Proident et consect', 'Consequatur repellen', NULL, 'Nevada Riggs', 'Deleniti saepe eos', '25-May-2017', 'Fulton and Newton Associates', 'Sed laboris aperiam', 'Pamela Hobbs', 'Ullamco maiores veli', '06-Apr-2018', 'Crosby and Dominguez Trading', 'Luna Daniel LLC', 'Frank Patton Trading', 'Hic atque fugit ear', '2025-08-15 05:02:08', '2025-08-15 05:02:08'),
(3, 'Laboris dolores omni', 'application_form/documents/1755296145_image-Picsart-AiImageEnhancer.png', 'Magna architecto con', 'Dolores enim in veni', 'application_form/profile/1755296146_image-Picsart-AiImageEnhancer.png', 'Cara Strong', 'Kidd', 'Carson Thomas', 'Dunlap', '05-Nov-1992', 'In omnis voluptatibu', 'In qui irure Nam vol', '1997-05-05', '1991-10-27', 'Ut dolor rem esse ve', 'Esse dolorum proiden', '1980-05-27', '2018-05-07', '1976-02-12', '1990-07-04', 'quze@mailinator.com', 'Qui est fugiat Nam', '+1 (725) 475-5341', 'Do est nesciunt acc', '10-Dec-1977', 'Quis repellendus Ma', 'Illo ab culpa totam', '464', 'Recusandae Consequu', 'Voluptatem ducimus', '2025-08-16', 'Veniam amet mollit', 'Corporis velit dolor', 'Sint accusantium eaq', 'Ut et dolor reprehen', 'Voluptate consequat', 'Quo labore ex iure n', 'Esse consequuntur fu', 'Other', 'on', 'Sean Knowles', '283', 'Culpa ea laborum M', '1997-11-13', 'Noelani Jarvis', 'Laudantium velit ma', 'Et animi asperiores', NULL, 'Cole Albert', 'Vel ullamco praesent', '26-Jun-1989', 'Cummings Reilly LLC', 'Quam et eos esse d', 'Shelly Lawrence', 'Expedita harum ut re', '01-Aug-2017', 'Munoz and Horton Traders', 'Christensen Britt Plc', '2025-08-15', 'Hic aut proident di', '2025-08-15 22:15:45', '2025-08-15 22:15:45'),
(4, 'Facere reprehenderit', 'application_form/documents/1755296246_image-Picsart-AiImageEnhancer.png', 'Repudiandae deleniti', 'Incidunt distinctio', 'application_form/profile/1755296247_image-Picsart-AiImageEnhancer.png', 'Hadassah Wyatt', 'Brewer', 'Christine Wilcox', 'Foreman', '23-Feb-2003', 'Qui magna velit offi', 'Ex dolore et adipisi', '2012-03-17', '1985-01-28', 'Aut non deserunt vol', 'Minus possimus fugi', '2023-09-09', '1994-03-19', '2017-01-24', '1973-05-22', 'zocudarufa@mailinator.com', 'Ut consequat Hic do', '+1 (782) 612-2588', 'Vel voluptatibus con', '10-Mar-2019', 'Ea accusantium tempo', 'Incidunt hic sequi', '770', 'Expedita est dignis', 'Aut voluptatem Aut', '1992-06-17', 'Molestiae omnis eum', 'Delectus eos harum', 'Magni minus laudanti', 'Proident in natus c', 'Odio totam aut excep', 'Ut laudantium culpa', 'Iste et necessitatib', 'Other', 'on', 'Howard Long', '413', 'Corporis asperiores', '1980-02-16', 'Kim Stanley', 'In omnis fuga Irure', 'Lorem architecto occ', NULL, 'Chadwick Mccullough', 'Velit proident magn', '31-Dec-1987', 'Allison and Santos Associates', 'Ex eaque quisquam ut', 'Kay West', 'Sit inventore repudi', '28-Nov-2013', 'Jimenez and Mcmahon Trading', 'Oneal Ramsey Associates', '1978-01-17', 'Voluptatem Repellen', '2025-08-15 22:17:26', '2025-08-15 22:17:26')";

        DB::insert($query);
    }
}
