<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DigitalForm extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $query="INSERT INTO `digitalforms` (`id`, `title`, `desc`, `success_message`, `failure_message`, `receiver_mail`, `order`, `parent_id`, `paginate_status`, `last_footer`, `mail_desc`, `header_status`, `invoice_to`, `invoice_from`, `sia`, `vat`, `tax_date`, `invoice_number`, `terms`, `due_date`, `invoice_date`, `created_at`, `updated_at`) VALUES
(14, 'Supreme Protection DOB Report', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-OP-02)-04</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', 'Successfullly submit', 'Message Failed', 'prodoc@gmail.com', 2, '0', 0, 1, '<p><br></p>', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-03-25 06:40:31', '2025-09-09 15:24:12'),
(16, 'Supreme Protection Incident Report Form', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-OP-02)-11</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', 'send Successfully', 'Failed Message', NULL, 3, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-03-27 22:30:01', '2025-07-20 14:34:12'),
(17, 'Employee Feedback Form', '<strong>OFFICE USE ONLY: Record any actions here to improve staff perception</strong><br>\r\n<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;font-weight: 200;\">F-(SOP-HR-01)-62</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;font-weight: 200;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;font-weight: 200;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;font-weight: 200;\">150 Chingford Rd, London, England, E17 4PL</span><br>', NULL, NULL, NULL, 4, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-03-27 22:58:31', '2025-04-04 19:18:06'),
(18, 'Site Visit Quality Control and Welfare Check Form', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-OP-02)-60</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">2</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">30/05/2024</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', NULL, NULL, NULL, 5, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-03-29 19:48:38', '2025-04-04 19:16:37'),
(19, 'Client Feedback Form', '<strong style=\"font-size: 15px;font-weight: bold;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-QA-10)-02</span><br>\r\n                <strong style=\"font-size: 15px;font-weight: bold;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;font-weight: bold;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;font-weight: bold;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', NULL, NULL, NULL, 5, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-03 16:40:04', '2025-04-04 19:25:00'),
(20, 'Consumer Feedback', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-QA-10)-03</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', NULL, NULL, NULL, 6, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-03 17:04:04', '2025-04-04 19:18:57'),
(21, 'Holiday Request Form', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-HR-01)-13</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', NULL, NULL, NULL, 7, '0', 1, 0, '<p><b>mail for test</b></p>', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-12 16:50:10', '2025-04-12 18:03:55'),
(22, 'Monthly Site Health and Safety Inspection Checklist', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-OP-05)--04</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', NULL, NULL, NULL, 8, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-12 21:09:01', '2025-04-13 07:49:19'),
(23, 'Site Induction', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-OP-02)--19</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', NULL, NULL, NULL, 9, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-12 21:27:41', '2025-04-12 22:07:08'),
(24, 'Uniform Issue Record Form', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\">F-(SOP-OP-02)--14</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', NULL, NULL, NULL, 10, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-12 22:13:57', '2025-04-13 22:53:35'),
(25, 'Complaint Registration Form', '<strong style=\"font-size: 15px;\">Reference No:</strong><span style=\"font-size: 15px;\"> F-(SOP-OP-03)-01 </span><br>\r\n                <strong style=\"font-size: 15px;\">Issue No: </strong><span style=\"font-size: 15px;\">1</span><br>\r\n                <strong style=\"font-size: 15px;\">Issue Date: </strong><span style=\"font-size: 15px;\">02/01/2023</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', 'Successfully submit', 'Message Failed', 'prodoc@gmail.com', 11, '0', 0, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-13 17:58:17', '2025-04-15 01:39:47'),
(26, 'Suggestion Form', '<strong style=\"font-size: 15px;\">Supreme Protection Limited</strong><br>\r\n                <strong style=\"font-size: 15px;\">Telephone: </strong><span style=\"font-size: 15px;\">02070783993</span><br>\r\n                <strong style=\"font-size: 15px;\">Address:</strong><span style=\"font-size: 15px;\">150 Chingford Rd, London, England, E17 4PL</span><br>', 'Successfully submit', 'Message Failed', 'prodoc@gmail.com', 12, '0', 0, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-15 01:40:03', '2025-04-15 02:18:13'),
(27, 'Invoice Form', NULL, NULL, NULL, NULL, 13, '0', 0, 0, '<p><br></p>', '1', 'AK9 Security Ltd', 'Kennedy Ansu 3430 newhamway London E16 4ED', 'UTR-8738695508 N.E', 'N/A', NULL, 'jun2023', '31', '2023-06-30', '2023-12-07', '2025-05-30 12:37:46', '2025-06-12 04:36:24'),
(28, 'Evaluation Test', NULL, 'Successfullly submit', 'Message Failed', 'prodoc@gmail.com', 14, '0', 1, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-07-23 07:57:44', '2025-07-23 08:53:20'),
(29, 'Accident, Incident, First Aid and Safeguarding, Reporting Form', NULL, NULL, NULL, NULL, 15, '0', 0, 0, NULL, '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-08-19 16:20:28', '2025-08-19 16:20:28')";

        DB::insert($query);
    }
}
