<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>All Incident Reports</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #333;
            line-height: 1.4;
        }

        h1, h2, h3 {
            margin: 0 0 10px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table th, table td {
            border: 1px solid #aaa;
            padding: 6px 10px;
            text-align: left;
            font-size: 12px;
        }

        table th {
            background-color: #f2f2f2;
        }

        .incident-title {
            background-color: #eee;
            font-weight: bold;
            padding: 4px 8px;
        }

        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 10px;
            color: #888;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>

    <h1>All Incident Reports</h1>
    <p>Total Reports: {{ count($incidents) }}</p>

    @foreach($incidents as $incident)
        <table>
            <tr>
                <th>ID</th>
                <td>{{ $incident->id }}</td>
                <th>Reported At</th>
                <td>{{ $incident->created_at?->format('Y-m-d H:i') }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td colspan="3">{{ $incident->title }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ ucfirst(str_replace('_', ' ', $incident->category)) }}</td>
                <th>Severity</th>
                <td>{{ ucfirst($incident->severity) }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ ucfirst(str_replace('_', ' ', $incident->status)) }}</td>
                <th>Police Notified</th>
                <td>{{ $incident->police_notified ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td colspan="3">{{ $incident->formatted_address ?? '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td colspan="3">{{ $incident->description ?? 'N/A' }}</td>
            </tr>
        </table>

        <div class="page-break"></div>
    @endforeach

    <div class="footer">
        Generated by {{ config('app.name') }} on {{ now()->format('Y-m-d H:i') }}
    </div>

</body>
</html>
