<?php

/**
 * Web CRM route → Spatie permission map.
 *
 * Exact route names win; patterns with * are checked next; URI fallbacks last.
 * Values may be a string or an array (OR — any permission grants access).
 */

return [

    'map' => [

        // ── Dashboard (any authenticated CRM user with a module permission, or just auth)
        // Left unmapped intentionally — auth + DenySecurityStaff is enough.

        // ── Security Board / Roster / Shifts
        'shifts.index' => 'Read Security Board',
        'shifts.scheduling' => 'Read Security Board',
        'shifts.worker_calendar' => 'Read Security Board',
        'shifts.site_calendar' => 'Read Security Board',
        'shifts.today_rota' => 'Read Security Board',
        'shifts.show' => 'Read Security Board',
        'shifts.filter' => 'Read Security Board',
        'shifts.export.excel' => 'Export Security Board',
        'shifts.export.pdf' => 'Export Security Board',
        'shifts.import' => 'Import Security Board',
        'shifts.store' => 'Create Security Board',
        'shifts.update' => 'Write Security Board',
        'shifts.updateSimple' => 'Write Security Board',
        'shifts.edit' => 'Write Security Board',
        'shifts.destroy' => 'Delete Security Board',
        'shifts.bulkDelete' => 'Delete Security Board',
        'shifts.unassign' => 'Write Security Board',
        'shifts.bulkUnassign' => 'Write Security Board',
        'shifts.multi-assign' => 'Write Security Board',
        'shifts.multiEdit' => 'Write Security Board',
        'shifts.assign' => 'Write Security Board',
        'shifts.store.override' => 'Write Security Board',
        'shiftDates.view' => 'Read Security Board',
        'shiftDates.tabs.*' => 'Read Security Board',
        'shift.note.*' => 'Write Security Board',
        'shift.map' => 'Read Security Board',
        'shift.bookon.store' => 'Write Security Board',
        'shift.bookoff.store' => 'Write Security Board',
        'shift.locations' => 'Read Security Board',
        'checkcalls.*' => ['Read Security Board', 'Write Security Board'],
        'patrol.*' => ['Read Security Board', 'Write Security Board'],
        'patrols.export.*' => 'Export Security Board',
        'getMonthlyShiftsStats' => 'Read Security Board',
        'bookrecords.acknowledge' => 'Write Security Board',
        'assign.shift.override' => 'Write Security Board',
        'shifts.update.override' => 'Write Security Board',
        'track.site' => 'Read Security Board',

        // ── Security Staff / Employees / Subcontractors
        'employees.index' => 'Read Security Staff',
        'employees.view' => 'Read Security Staff',
        'employees.print' => 'Read Security Staff',
        'employees.edit' => 'Write Security Staff',
        'employees.update' => 'Write Security Staff',
        'employees.store' => 'Create Security Staff',
        'employees.delete' => 'Delete Security Staff',
        'employees.pendingDeletes' => 'Write Security Staff',
        'employees.pendingDeletes.*' => 'Write Security Staff',
        'employee.bulkDelete' => 'Delete Security Staff',
        'employees.logs.*' => 'Read Security Staff',
        'employees.logs.email' => 'Read Security Staff',
        'employees.export.*' => 'Export Security Staff',
        'employees.import' => 'Import Security Staff',
        'employees.documents.*' => 'Write Security Staff',
        'documents.byUser' => 'Read Security Staff',
        'documents.report' => 'Read Reports Managment',
        'documents.report.export.*' => 'Export Reports Managment',
        'device-change-requests.*' => 'Write Security Staff',
        'subcontractors.*' => 'Read Security Staff',
        'subcontractors.index' => 'Read Security Staff',
        'subcontractors.store' => 'Create Security Staff',
        'subcontractors.edit' => 'Write Security Staff',
        'subcontractors.update' => 'Write Security Staff',
        'subcontractors.delete' => 'Delete Security Staff',
        'subcontractors.bulkDelete' => 'Delete Security Staff',
        'subcontractors.view' => 'Read Security Staff',
        'subcontractors.employees' => 'Read Security Staff',
        'subcontractors.logs.ajax' => 'Read Security Staff',
        'subcontractors.forEmployee' => 'Read Security Staff',
        'subcontractors.export.*' => 'Export Security Staff',
        'subcontractors.import' => 'Import Security Staff',

        // ── Clients / Sites
        'clients.index' => 'Read Clients',
        'clients.store' => 'Create Clients',
        'clients.edit' => 'Write Clients',
        'clients.update' => 'Write Clients',
        'clients.delete' => 'Delete Clients',
        'clients.bulkDelete' => 'Delete Clients',
        'clients.view' => 'Read Clients',
        'clients.logs.ajax' => 'Read Clients',
        'clients.assignManager' => 'Write Clients',
        'clients.export.*' => 'Export Clients',
        'clients.import' => 'Import Clients',
        'sites.index' => 'Read Clients',
        'sites.store' => 'Create Clients',
        'sites.edit' => 'Write Clients',
        'sites.update' => 'Write Clients',
        'sites.delete' => 'Delete Clients',
        'sites.bulkDelete' => 'Delete Clients',
        'sites.view' => 'Read Clients',
        'sites.logs.ajax' => 'Read Clients',
        'sites.generateQr' => 'Write Clients',
        'sites.generateNfc' => 'Write Clients',
        'sites.geocode' => 'Write Clients',
        'sites.export.*' => 'Export Clients',
        'sites.import' => 'Import Clients',
        'holidays.list' => 'Read Clients',
        'impersonate.start' => 'Read Clients',

        // ── User Management
        'users.index' => 'Read User Management',
        'users.store' => 'Create User Management',
        'users.edit' => 'Write User Management',
        'users.update' => 'Write User Management',
        'users.destroy' => 'Delete User Management',
        'users.bulkDelete' => 'Delete User Management',
        'users.view' => 'Read User Management',
        'users.logs.ajax' => 'Read User Management',
        'users.export.*' => 'Export User Management',
        'users.import' => 'Import User Management',
        'roles.index' => 'Read User Management',
        'roles.store' => 'Create User Management',
        'roles.update' => 'Write User Management',
        'roles.destroy' => 'Delete User Management',
        'roles.bulkDelete' => 'Delete User Management',
        'roles.export.*' => 'Export User Management',
        'roles.import' => 'Import User Management',
        'permissions.*' => 'Read User Management',
        'permissions.bulkDelete' => 'Delete User Management',

        // ── Invoices / Payroll
        'invoices.index' => 'Read Invoice Management',
        'invoices.edit' => 'Write Invoice Management',
        'invoices.store' => 'Create Invoice Management',
        'invoices.sub' => 'Create Invoice Management',
        'invoices.show' => 'Read Invoice Management',
        'invoices.delete' => 'Delete Invoice Management',
        'invoices.bulkDelete' => 'Delete Invoice Management',
        'invoices.export.*' => 'Export Invoice Management',
        'payrolls.index' => 'Read Invoice Management',
        'payrolls.subcontractor.data' => 'Read Invoice Management',
        'payroll.edit' => 'Write Invoice Management',
        'payroll.store' => 'Create Invoice Management',
        'payroll.generatepayroll_subcontractor' => 'Create Invoice Management',
        'payrolls.show' => 'Read Invoice Management',
        'payrolls.delete' => 'Delete Invoice Management',
        'payrolls.bulkDelete' => 'Delete Invoice Management',

        // ── Vehicles
        'vehicle.management' => 'Read Vehicle Management',
        'vehicle.data' => 'Read Vehicle Management',
        'vehicle_details' => 'Read Vehicle Management',
        'vehicles.store' => 'Create Vehicle Management',
        'vehicles.edit' => 'Write Vehicle Management',
        'vehicles.update' => 'Write Vehicle Management',
        'vehicles.delete' => 'Delete Vehicle Management',
        'vehicles.bulkDelete' => 'Delete Vehicle Management',
        'vehicles.export.*' => 'Export Vehicle Management',
        'vehicles.import' => 'Import Vehicle Management',
        'documents' => 'Read Vehicle Management',
        'documents.data' => 'Read Vehicle Management',
        'documents.store' => 'Create Vehicle Management',
        'documents.edit' => 'Write Vehicle Management',
        'documents.update' => 'Write Vehicle Management',
        'documents.delete' => 'Delete Vehicle Management',
        'documents.bulkDelete' => 'Delete Vehicle Management',
        'compliances.export.*' => 'Export Vehicle Management',
        'compliances.import' => 'Import Vehicle Management',
        'maintenances.export.*' => 'Export Vehicle Management',
        'maintenances.import' => 'Import Vehicle Management',
        'checks.export.*' => 'Export Vehicle Management',
        'checks.import' => 'Import Vehicle Management',
        'reminders.export.*' => 'Export Vehicle Management',
        'reminders.import' => 'Import Vehicle Management',

        // ── Restrictions
        'restrictions.index' => 'Read Restrictions',
        'restrictions.toggle' => 'Write Restrictions',

        // ── Holiday / Leaves
        'leaves.index' => 'Read Holiday Managment',
        'leaves.store' => 'Create Holiday Managment',
        'leaves.update' => 'Write Holiday Managment',
        'leaves.edit' => 'Write Holiday Managment',
        'leaves.destroy' => 'Delete Holiday Managment',
        'leaves.view' => 'Read Holiday Managment',
        'leaves.logs.ajax' => 'Read Holiday Managment',
        'leaves.pending' => 'Write Holiday Managment',
        'leaves.approve' => 'Write Holiday Managment',
        'leaves.reject' => 'Write Holiday Managment',
        'leaves.bulkDelete' => 'Delete Holiday Managment',
        'leaves.export.*' => 'Export Holiday Managment',
        'calendar' => 'Read Holiday Managment',

        // ── HR / Training materials
        'materials.index' => 'Read HR Managment',
        'materials.store' => 'Create HR Managment',
        'materials.update' => 'Write HR Managment',
        'materials.destroy' => 'Delete HR Managment',
        'materials.bulkDelete' => 'Delete HR Managment',
        'materials.show' => 'Read HR Managment',
        'materials.export.*' => 'Export HR Managment',
        'show.acknowledged' => 'Read HR Managment',

        // ── Reports
        'reports.sia' => 'Read Reports Managment',
        'reports.sia.show' => 'Read Reports Managment',
        'reports.sia.debug' => 'Read Reports Managment',
        'reports.sia.csv' => 'Export Reports Managment',
        'reports.sia.delete' => 'Delete Reports Managment',
        'reports.employment' => 'Read Reports Managment',
        'reports.employment.pdf' => 'Export Reports Managment',
        'availability.report' => 'Read Reports Managment',
        'staff.report' => 'Read Reports Managment',
        'reports.shift' => 'Read Reports Managment',
        'booking.report' => 'Read Reports Managment',
        'reports.clients' => 'Read Reports Managment',
        'report.checkpoints' => 'Read Reports Managment',
        'report.checkcalls_patrols' => 'Read Reports Managment',
        'performance.report' => 'Read Reports Managment',
        'salary.report' => 'Read Reports Managment',
        'reports.logins' => 'Read Reports Managment',
        'incident_report.*' => 'Read Reports Managment',
        'incidents.*' => 'Read Reports Managment',
        'incidents.index' => 'Read Reports Managment',
        'incidents.show' => 'Read Reports Managment',
        'incidents.edit' => 'Write Reports Managment',
        'incidents.update' => 'Write Reports Managment',
        'incidents.store' => 'Create Reports Managment',
        'incidents.destroy' => 'Delete Reports Managment',
        'incidents.bulkdelete' => 'Delete Reports Managment',
        'incidents.updateStatus' => 'Write Reports Managment',
        'dobs.*' => 'Read Reports Managment',
        'dobs.index' => 'Read Reports Managment',
        'dobs.store' => 'Create Reports Managment',
        'dobs.show' => 'Read Reports Managment',
        'dobs.edit' => 'Write Reports Managment',
        'dobs.update' => 'Write Reports Managment',
        'dobs.destroy' => 'Delete Reports Managment',
        'dobs.bulkDelete' => 'Delete Reports Managment',
        'dobs.export.*' => 'Export Reports Managment',
        'logs.index' => 'Read Reports Managment',

        // ── Chat
        'chat.index' => 'Read Chat',
        'conversations' => 'Create Chat',
        'load.conversations' => 'Read Chat',
        'conversations.messages' => 'Read Chat',
        'conversations.sendMessage' => 'Write Chat',
        'messages.delete' => 'Delete Chat',
        'conversations.members' => 'Read Chat',
        'conversations.delete' => 'Delete Chat',
        'conversations.togglePin' => 'Write Chat',
        'create.one.to.one' => 'Create Chat',
        'conversations.typing' => 'Write Chat',
        'conversations.markAsRead' => 'Write Chat',
        'conversations.media' => 'Read Chat',

        // ── Notifications (any authenticated CRM user)
        // left unmapped — auth only

        'client.report.export.pdf' => 'Export Reports Managment',
        'client.report.export.excel' => 'Export Reports Managment',
        'assign.shift.override.multi' => 'Write Security Board',
        'process.sia.licences' => 'Write Security Staff',
        'process.shift.notifications' => 'Write Security Board',

        // ── Docs / Digital forms (permissions from PermissionSeeder)
        'admin.setting.index' => 'General Settings',
        'admin.setting.create' => 'General Settings',

        'digital.form.index' => 'digitalform list',
        'digital.form.create' => 'digitalform create',
        'digital.form.store' => 'digitalform create',
        'digital.form.edit' => 'digitalform edit',
        'digital.form.update' => 'digitalform edit',
        'digital.form.destroy' => 'digitalform delete',
        'digital.form.order' => 'digitalform edit',
        'paginate.update.status' => 'digitalform edit',

        'digital.form.fields' => 'dynamicinput',
        'digital.form.fields.create' => 'dynamicinput create',
        'digital.form.fields.store' => 'dynamicinput create',
        'digital.form.field.edit' => 'dynamicinput edit',
        'digital.form.field.update' => 'dynamicinput edit',
        'digital.form.field.destroy' => 'dynamicinput delete',
        'digital.form.field.order' => 'dynamicinput edit',
        'digital.form.fields.child' => 'dynamicinput',
        'digital.form.fields.create.child' => 'dynamicinput create',
        'digital.form.fields.store.child' => 'dynamicinput create',
        'digital.form.field.edit.child' => 'dynamicinput edit',
        'digital.form.field.update.child' => 'dynamicinput edit',
        'digital.form.field.destroy.child' => 'dynamicinput delete',
        'digital.form.field.child.order' => 'dynamicinput edit',
        'update.status' => 'dynamicinput edit',

        'page.form.index' => 'page list',
        'page.form.create' => 'page create',
        'page.form.store' => 'page create',
        'page.form.edit' => 'page edit',
        'page.form.update' => 'page edit',
        'page.form.destroy' => 'page delete',

        'clientdetail.index' => 'form list',
        'form_detail.index' => 'client detail list',
        'form_detail.edit' => 'client detail edit',
        'form_detail.update' => 'client detail edit',
        'client.complete.detail.index' => 'client complete detail',
        'client.complete.detail.update' => 'client complete detail',
        'clientdetail.destroy' => 'client detail destroy',
        'delete.file' => 'client detail destroy',
        'mail.send' => 'client detail list',

        'application.form.show' => 'applicationform view',
        'application.form.edit' => 'applicationform edit',
        'application.form.incident.data' => 'incidentform edit',
        'application.form.incident.data.view' => 'incidentform edit',
    ],

    /*
    |--------------------------------------------------------------------------
    | URI fallbacks (for routes without names / outside auth groups)
    |--------------------------------------------------------------------------
    */
    'uri' => [
        '/scheduling' => 'Read Security Board',
        '/worker_calendar' => 'Read Security Board',
        '/site_calendar' => 'Read Security Board',
        '/today_rota' => 'Read Security Board',
        '/shifts*' => ['Read Security Board', 'Write Security Board', 'Create Security Board', 'Delete Security Board'],
        '/shift-dates*' => 'Read Security Board',
        '/checkcalls*' => 'Write Security Board',
        '/check-calls*' => 'Write Security Board',
        '/patrols*' => 'Write Security Board',
        '/create/checkcall' => 'Create Security Board',
        '/create/patrol' => 'Create Security Board',
        '/assign-shift*' => 'Write Security Board',
        '/api/shifts*' => 'Read Security Board',
        '/api/client/*' => 'Read Security Board',
        '/api/staff/*' => 'Read Security Board',
        '/api/subcontractor/*' => 'Read Security Board',
        '/generate-heatmap' => 'Read Security Board',
        '/track/site/*' => 'Read Security Board',
        '/weekly-hours-alerts' => 'Read Reports Managment',
        '/optimize-server' => 'Read User Management',
        '/process-shift-notifications' => 'Write Security Board',

        '/employees*' => ['Read Security Staff', 'Write Security Staff', 'Create Security Staff', 'Delete Security Staff'],
        '/editemployee/*' => 'Write Security Staff',
        '/deleteemployee/*' => 'Delete Security Staff',
        '/updateemployee/*' => 'Write Security Staff',
        '/subcontractors*' => ['Read Security Staff', 'Write Security Staff'],
        '/editsubcontractor/*' => 'Write Security Staff',
        '/deletesubcontractor/*' => 'Delete Security Staff',
        '/updatesubcontractor/*' => 'Write Security Staff',
        '/subcontractor/*' => 'Read Security Staff',
        '/process-sia-licences' => 'Write Security Staff',
        '/device-change-requests*' => 'Write Security Staff',

        '/clients*' => ['Read Clients', 'Write Clients', 'Create Clients', 'Delete Clients'],
        '/editclient/*' => 'Write Clients',
        '/deleteclient/*' => 'Delete Clients',
        '/updateclient/*' => 'Write Clients',
        '/sites*' => ['Read Clients', 'Write Clients', 'Create Clients', 'Delete Clients'],
        '/editsite/*' => 'Write Clients',
        '/deletesite/*' => 'Delete Clients',
        '/updatesite/*' => 'Write Clients',
        '/holidays' => 'Read Clients',
        '/impersonate/*' => 'Read Clients',

        '/users*' => ['Read User Management', 'Write User Management', 'Create User Management', 'Delete User Management'],
        '/edituser/*' => 'Write User Management',
        '/deleteuser/*' => 'Delete User Management',
        '/roles*' => ['Read User Management', 'Write User Management'],
        '/deleterole/*' => 'Delete User Management',
        '/permissions*' => 'Read User Management',
        '/deletepermission/*' => 'Delete User Management',

        '/invoices*' => ['Read Invoice Management', 'Write Invoice Management', 'Create Invoice Management', 'Delete Invoice Management'],
        '/generateinvoice*' => ['Create Invoice Management', 'Write Invoice Management'],
        '/deleteinvoice/*' => 'Delete Invoice Management',
        '/payrolls*' => ['Read Invoice Management', 'Write Invoice Management'],
        '/generatepayroll*' => ['Create Invoice Management', 'Write Invoice Management'],
        '/deletepayroll/*' => 'Delete Invoice Management',

        '/vehicle*' => ['Read Vehicle Management', 'Write Vehicle Management'],
        '/documentation_uploads*' => ['Read Vehicle Management', 'Write Vehicle Management'],
        '/editdocument/*' => 'Write Vehicle Management',
        '/deletedocument/*' => 'Delete Vehicle Management',
        '/updatedocument/*' => 'Write Vehicle Management',
        '/documents*' => ['Read Vehicle Management', 'Read Reports Managment', 'Write Vehicle Management'],
        '/compliances*' => 'Read Vehicle Management',
        '/maintenances*' => 'Read Vehicle Management',
        '/checks*' => 'Read Vehicle Management',
        '/reminders*' => 'Read Vehicle Management',

        '/settings/restrictions*' => ['Read Restrictions', 'Write Restrictions'],

        '/leaves*' => ['Read Holiday Managment', 'Write Holiday Managment', 'Create Holiday Managment', 'Delete Holiday Managment'],
        '/editleave/*' => 'Write Holiday Managment',
        '/deleteleave/*' => 'Delete Holiday Managment',
        '/calendar' => 'Read Holiday Managment',

        '/hr*' => ['Read HR Managment', 'Write HR Managment', 'Create HR Managment', 'Delete HR Managment'],
        '/materials*' => ['Read HR Managment', 'Write HR Managment', 'Create HR Managment', 'Delete HR Managment'],

        '/admin/setting*' => 'General Settings',
        '/digital/form*' => ['digitalform list', 'digitalform create', 'digitalform edit', 'digitalform delete', 'dynamicinput', 'dynamicinput create', 'dynamicinput edit', 'dynamicinput delete'],
        '/page/form*' => ['page list', 'page create', 'page edit', 'page delete'],
        '/form/shows' => 'form list',
        '/form/client/*' => ['client detail list', 'client detail edit'],
        '/client/complete/*' => 'client complete detail',
        '/client/detail/*' => 'client detail destroy',
        '/application/form/show' => 'applicationform view',
        '/application/form/edit/*' => 'applicationform edit',
        '/User/form/incident/data/view/*' => 'incidentform edit',

        '/reports*' => ['Read Reports Managment', 'Export Reports Managment'],
        '/incident_report*' => 'Read Reports Managment',
        '/incidents*' => ['Read Reports Managment', 'Write Reports Managment', 'Create Reports Managment', 'Delete Reports Managment'],
        '/dobs*' => ['Read Reports Managment', 'Write Reports Managment', 'Create Reports Managment', 'Delete Reports Managment'],
        '/logs' => 'Read Reports Managment',
        '/logs/*' => 'Read Security Staff',

        '/chat*' => ['Read Chat', 'Write Chat'],
        '/conversations*' => ['Read Chat', 'Write Chat', 'Create Chat', 'Delete Chat'],
        '/load/conversations' => 'Read Chat',
        '/messages*' => ['Write Chat', 'Delete Chat'],
        '/create-one-to-one-conversation' => 'Create Chat',
        '/api/conversations*' => ['Read Chat', 'Write Chat'],
    ],

];
