content = (
    "<?php\n"
    "\n"
    "namespace App\\Console\\Commands;\n"
    "\n"
    "use Illuminate\\Console\\Command;\n"
    "use Illuminate\\Support\\Facades\\Log;\n"
    "\n"
    "class ProcessShiftNotifications extends Command\n"
    "{\n"
    "    protected $signature = 'shifts:process-notifications';\n"
    "\n"
    "    protected $description = 'Process and send shift notifications';\n"
    "\n"
    "    public function handle()\n"
    "    {\n"
    "        Log::info('Notification command started');\n"
    "\n"
    "        // Delegate entirely to the web controller which contains all logic\n"
    "        try {\n"
    "            $controller = new \\App\\Http\\Controllers\\ShiftNotificationController();\n"
    "            $controller->process(new \\Illuminate\\Http\\Request());\n"
    "        } catch (\\Throwable $e) {\n"
    "            Log::error('ShiftNotificationController::process failed: ' . $e->getMessage());\n"
    "        }\n"
    "\n"
    "        Log::info('Notification command ended');\n"
    "\n"
    "        // Close any lingering database connections\n"
    "        \\DB::disconnect();\n"
    "\n"
    "        $this->info('Shift notifications processed successfully.');\n"
    "    }\n"
    "}\n"
)

path = r"c:\Users\Yousif\Downloads\Compressed\_supreme-3\app\Console\Commands\ProcessShiftNotifications.php"
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("Done")
